version: "3.9"

services:
  mysvc:
    image: tharun29012000/myimage:zomato
    ports:
      - "3001:3000"   # maps targetPort 3000 to host port 3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - swiggy-net
    labels:
      app: swiggy

networks:
  swiggy-net:
    driver: overlay

